version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: idroove_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'idroove_db'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
